services:
  chat:
    image: "${IMAGE:-your-dockerhub-namespace/node-chat-app}:${IMAGE_TAG:-latest}"
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
